import { readFileSync, writeFileSync } from 'node:fs';

const FILES = {
  uz: 'apps/web/src/messages/uz.json',
  ru: 'apps/web/src/messages/ru.json',
  en: 'apps/web/src/messages/en.json',
};

const NS = {
  uz: {
    title: 'Sug‘urta — bir joyda, aniq narxda',
    subtitle: 'OSAGO, KASKO, sayohat, uy va sog‘liq sug‘urtasini onlayn hisoblang va 2 daqiqada rasmiylashtiring.',
    badge: 'Izla Sug‘urta',
    point1: 'Aniq narx — yashirin to‘lovsiz',
    point2: 'Elektron polis (e-polis)',
    point3: 'Litsenziyalangan kompaniyalar',
    myPoliciesLink: 'Mening polislarim',
    backToList: 'Barcha mahsulotlar',
    types: {
      OSAGO: { name: 'OSAGO' },
      KASKO: { name: 'KASKO' },
      TRAVEL: { name: 'Sayohat' },
      PROPERTY: { name: 'Uy-joy' },
      ACCIDENT: { name: 'Baxtsiz hodisa' },
      HEALTH: { name: 'Tibbiy (VMD)' },
    },
    filter: {
      title: 'Filtr', type: 'Sug‘urta turi', allTypes: 'Barcha turlar', insurer: 'Kompaniya',
      maxPrice: 'Narx (gacha)', term: 'Muddat', sort: 'Saralash',
      sortPopular: 'Ommabop', sortPriceAsc: 'Avval arzon', sortPriceDesc: 'Avval qimmat', sortRating: 'Reyting',
      clear: 'Tozalash', results: '{count} ta mahsulot', popular: 'Ommabop', empty: 'Mos mahsulot topilmadi',
    },
    card: { from: 'dan boshlab', coverage: 'Qoplama', calculate: 'Hisoblash' },
    calc: {
      heading: 'Narxni hisoblang', configure: 'Parametrlarni tanlang', premium: 'Sug‘urta narxi',
      coverage: 'Qoplama summasi', breakdown: 'Hisob-kitob tafsiloti', months: 'oy',
      buy: 'Rasmiylashtirish', loginBuy: 'Kirish va rasmiylashtirish', buying: 'Rasmiylashtirilmoqda…',
      done: 'Polis rasmiylashtirildi', doneTitle: 'Tayyor!', doneMsg: 'Polisingiz «Mening polislarim» bo‘limida saqlandi.',
      policyNo: 'Polis raqami', viewPolicies: 'Polislarim', again: 'Yana hisoblash',
      disclaimer: 'Narxlar taxminiy — yakuniy summa rasmiylashtirishda tasdiqlanadi.',
    },
    fields: {
      vehicle: 'Transport turi', region: 'Hudud', drivers: 'Haydovchilar', experience: 'Haydovchi staji',
      period: 'Muddat', carValue: 'Avtomobil qiymati', carAge: 'Avtomobil yoshi', franchise: 'Franshiza',
      days: 'Kunlar soni', coverage: 'Qoplama (USD)', travelAge: 'Sayohatchi yoshi', travelers: 'Sayohatchilar',
      propertyValue: 'Mol-mulk qiymati', kind: 'Obyekt turi', insuredSum: 'Qoplama summasi',
      occupation: 'Kasb', persons: 'Insonlar soni', plan: 'Paket', healthAge: 'Yosh', dental: 'Stomatologiya', term: 'Muddat',
    },
    opt: {
      vehicle: { car: 'Yengil avto', suv: 'Krossover', truck: 'Yuk mashina', bus: 'Avtobus', moto: 'Mototsikl' },
      region: { toshkent_shahar: 'Toshkent sh.', toshkent_viloyat: 'Toshkent vil.', boshqa: 'Boshqa viloyat' },
      drivers: { limited: 'Cheklangan', unlimited: 'Cheklanmagan' },
      experience: { lt2: '2 yildan kam', mid: '2–5 yil', exp: '5 yildan ortiq' },
      period: { '12': '12 oy', '6': '6 oy' },
      carage: { new: '0–3 yil', mid: '3–7 yil', old: '7 yildan katta' },
      franchise: { none: 'Franshizasiz', low: '1%', high: '3%' },
      travelregion: { cis: 'MDH', schengen: 'Shengen', world: 'Butun dunyo' },
      travelage: { child: '0–17 yosh', adult: '18–64 yosh', senior: '65+ yosh' },
      travelcov: { '30000': '$30 000', '50000': '$50 000', '100000': '$100 000' },
      kind: { apartment: 'Kvartira', house: 'Uy', dacha: 'Dala hovli' },
      occupation: { office: 'Ofis', worker: 'Ishlab chiqarish', extreme: 'Xavfli' },
      plan: { standart: 'Standart', kengaytirilgan: 'Kengaytirilgan', premium: 'Premium' },
      healthage: { young: '18–35 yosh', mid: '36–55 yosh', senior: '56+ yosh' },
    },
    trust: { licensed: 'Litsenziyalangan sug‘urta kompaniyasi', coverageFrom: 'Qoplama {sum} dan' },
    attach: {
      eyebrow: 'Qo‘shimcha himoya',
      autoTitle: 'Avtomobilingizni sug‘urtalang', autoText: 'OSAGO yoki KASKO’ni shu yerdan onlayn rasmiylashtiring.',
      travelTitle: 'Sayohatga chiqyapsizmi?', travelText: 'Sayohat sug‘urtasini 2 daqiqada oling.',
      healthTitle: 'Sog‘lig‘ingizni himoyalang', healthText: 'Tibbiy sug‘urta (VMD) — eng yaxshi klinikalar tarmog‘i.',
      cta: 'Hisoblash',
    },
    policies: {
      title: 'Mening polislarim', subtitle: 'Rasmiylashtirilgan sug‘urta polislaringiz',
      loginNeeded: 'Polislaringizni ko‘rish uchun tizimga kiring', login: 'Kirish',
      empty: 'Hozircha polis yo‘q', emptyCta: 'Sug‘urta tanlash', until: 'Amal qiladi',
      status: { DRAFT: 'Qoralama', PENDING: 'To‘lov kutilmoqda', ACTIVE: 'Faol', EXPIRED: 'Muddati tugagan', CANCELLED: 'Bekor qilingan' },
    },
  },
  ru: {
    title: 'Страхование — в одном месте, по точной цене',
    subtitle: 'Рассчитайте ОСАГО, КАСКО, туристическую, имущественную и медицинскую страховку онлайн и оформите за 2 минуты.',
    badge: 'Izla Страхование',
    point1: 'Точная цена — без скрытых платежей',
    point2: 'Электронный полис (e-полис)',
    point3: 'Лицензированные компании',
    myPoliciesLink: 'Мои полисы',
    backToList: 'Все продукты',
    types: {
      OSAGO: { name: 'ОСАГО' },
      KASKO: { name: 'КАСКО' },
      TRAVEL: { name: 'Путешествия' },
      PROPERTY: { name: 'Недвижимость' },
      ACCIDENT: { name: 'Несчастный случай' },
      HEALTH: { name: 'Медицина (ДМС)' },
    },
    filter: {
      title: 'Фильтр', type: 'Тип страховки', allTypes: 'Все типы', insurer: 'Компания',
      maxPrice: 'Цена (до)', term: 'Срок', sort: 'Сортировка',
      sortPopular: 'Популярные', sortPriceAsc: 'Сначала дешёвые', sortPriceDesc: 'Сначала дорогие', sortRating: 'Рейтинг',
      clear: 'Сбросить', results: '{count} продуктов', popular: 'Популярно', empty: 'Подходящих продуктов не найдено',
    },
    card: { from: 'от', coverage: 'Покрытие', calculate: 'Рассчитать' },
    calc: {
      heading: 'Рассчитайте цену', configure: 'Выберите параметры', premium: 'Стоимость страховки',
      coverage: 'Сумма покрытия', breakdown: 'Детали расчёта', months: 'мес',
      buy: 'Оформить', loginBuy: 'Войти и оформить', buying: 'Оформляем…',
      done: 'Полис оформлен', doneTitle: 'Готово!', doneMsg: 'Ваш полис сохранён в разделе «Мои полисы».',
      policyNo: 'Номер полиса', viewPolicies: 'Мои полисы', again: 'Рассчитать снова',
      disclaimer: 'Цены ориентировочные — итоговая сумма подтверждается при оформлении.',
    },
    fields: {
      vehicle: 'Тип транспорта', region: 'Регион', drivers: 'Водители', experience: 'Стаж водителя',
      period: 'Срок', carValue: 'Стоимость авто', carAge: 'Возраст авто', franchise: 'Франшиза',
      days: 'Количество дней', coverage: 'Покрытие (USD)', travelAge: 'Возраст туриста', travelers: 'Туристы',
      propertyValue: 'Стоимость имущества', kind: 'Тип объекта', insuredSum: 'Сумма покрытия',
      occupation: 'Профессия', persons: 'Количество лиц', plan: 'Пакет', healthAge: 'Возраст', dental: 'Стоматология', term: 'Срок',
    },
    opt: {
      vehicle: { car: 'Легковой', suv: 'Кроссовер', truck: 'Грузовик', bus: 'Автобус', moto: 'Мотоцикл' },
      region: { toshkent_shahar: 'г. Ташкент', toshkent_viloyat: 'Ташкентская обл.', boshqa: 'Другой регион' },
      drivers: { limited: 'Ограниченный', unlimited: 'Неограниченный' },
      experience: { lt2: 'менее 2 лет', mid: '2–5 лет', exp: 'более 5 лет' },
      period: { '12': '12 мес', '6': '6 мес' },
      carage: { new: '0–3 года', mid: '3–7 лет', old: 'старше 7 лет' },
      franchise: { none: 'Без франшизы', low: '1%', high: '3%' },
      travelregion: { cis: 'СНГ', schengen: 'Шенген', world: 'Весь мир' },
      travelage: { child: '0–17 лет', adult: '18–64 года', senior: '65+ лет' },
      travelcov: { '30000': '$30 000', '50000': '$50 000', '100000': '$100 000' },
      kind: { apartment: 'Квартира', house: 'Дом', dacha: 'Дача' },
      occupation: { office: 'Офис', worker: 'Производство', extreme: 'Опасная' },
      plan: { standart: 'Стандарт', kengaytirilgan: 'Расширенный', premium: 'Премиум' },
      healthage: { young: '18–35 лет', mid: '36–55 лет', senior: '56+ лет' },
    },
    trust: { licensed: 'Лицензированная страховая компания', coverageFrom: 'Покрытие от {sum}' },
    attach: {
      eyebrow: 'Дополнительная защита',
      autoTitle: 'Застрахуйте автомобиль', autoText: 'Оформите ОСАГО или КАСКО онлайн прямо здесь.',
      travelTitle: 'Собираетесь в поездку?', travelText: 'Оформите туристическую страховку за 2 минуты.',
      healthTitle: 'Защитите своё здоровье', healthText: 'Медицинская страховка (ДМС) — сеть лучших клиник.',
      cta: 'Рассчитать',
    },
    policies: {
      title: 'Мои полисы', subtitle: 'Ваши оформленные страховые полисы',
      loginNeeded: 'Войдите, чтобы увидеть свои полисы', login: 'Войти',
      empty: 'Пока нет полисов', emptyCta: 'Выбрать страховку', until: 'Действует до',
      status: { DRAFT: 'Черновик', PENDING: 'Ожидает оплаты', ACTIVE: 'Активен', EXPIRED: 'Истёк', CANCELLED: 'Отменён' },
    },
  },
  en: {
    title: 'Insurance — one place, exact price',
    subtitle: 'Calculate OSAGO, KASKO, travel, property and health insurance online and get covered in 2 minutes.',
    badge: 'Izla Insurance',
    point1: 'Exact price — no hidden fees',
    point2: 'Electronic policy (e-policy)',
    point3: 'Licensed companies',
    myPoliciesLink: 'My policies',
    backToList: 'All products',
    types: {
      OSAGO: { name: 'OSAGO' },
      KASKO: { name: 'KASKO' },
      TRAVEL: { name: 'Travel' },
      PROPERTY: { name: 'Property' },
      ACCIDENT: { name: 'Accident' },
      HEALTH: { name: 'Health' },
    },
    filter: {
      title: 'Filter', type: 'Insurance type', allTypes: 'All types', insurer: 'Company',
      maxPrice: 'Price (up to)', term: 'Term', sort: 'Sort',
      sortPopular: 'Popular', sortPriceAsc: 'Cheapest first', sortPriceDesc: 'Most expensive', sortRating: 'Rating',
      clear: 'Clear', results: '{count} products', popular: 'Popular', empty: 'No matching products',
    },
    card: { from: 'from', coverage: 'Coverage', calculate: 'Calculate' },
    calc: {
      heading: 'Calculate the price', configure: 'Choose parameters', premium: 'Insurance price',
      coverage: 'Coverage amount', breakdown: 'Calculation details', months: 'mo',
      buy: 'Get covered', loginBuy: 'Sign in & buy', buying: 'Processing…',
      done: 'Policy issued', doneTitle: 'Done!', doneMsg: 'Your policy was saved in “My policies”.',
      policyNo: 'Policy number', viewPolicies: 'My policies', again: 'Calculate again',
      disclaimer: 'Prices are indicative — the final amount is confirmed at checkout.',
    },
    fields: {
      vehicle: 'Vehicle type', region: 'Region', drivers: 'Drivers', experience: 'Driver experience',
      period: 'Term', carValue: 'Car value', carAge: 'Car age', franchise: 'Deductible',
      days: 'Number of days', coverage: 'Coverage (USD)', travelAge: 'Traveler age', travelers: 'Travelers',
      propertyValue: 'Property value', kind: 'Object type', insuredSum: 'Coverage amount',
      occupation: 'Occupation', persons: 'Number of people', plan: 'Plan', healthAge: 'Age', dental: 'Dental', term: 'Term',
    },
    opt: {
      vehicle: { car: 'Car', suv: 'SUV', truck: 'Truck', bus: 'Bus', moto: 'Motorcycle' },
      region: { toshkent_shahar: 'Tashkent city', toshkent_viloyat: 'Tashkent region', boshqa: 'Other region' },
      drivers: { limited: 'Limited', unlimited: 'Unlimited' },
      experience: { lt2: 'under 2 years', mid: '2–5 years', exp: 'over 5 years' },
      period: { '12': '12 mo', '6': '6 mo' },
      carage: { new: '0–3 years', mid: '3–7 years', old: 'over 7 years' },
      franchise: { none: 'No deductible', low: '1%', high: '3%' },
      travelregion: { cis: 'CIS', schengen: 'Schengen', world: 'Worldwide' },
      travelage: { child: '0–17 years', adult: '18–64 years', senior: '65+ years' },
      travelcov: { '30000': '$30,000', '50000': '$50,000', '100000': '$100,000' },
      kind: { apartment: 'Apartment', house: 'House', dacha: 'Country house' },
      occupation: { office: 'Office', worker: 'Manufacturing', extreme: 'Hazardous' },
      plan: { standart: 'Standard', kengaytirilgan: 'Extended', premium: 'Premium' },
      healthage: { young: '18–35 years', mid: '36–55 years', senior: '56+ years' },
    },
    trust: { licensed: 'Licensed insurance company', coverageFrom: 'Coverage from {sum}' },
    attach: {
      eyebrow: 'Extra protection',
      autoTitle: 'Insure your car', autoText: 'Get OSAGO or KASKO online right here.',
      travelTitle: 'Going on a trip?', travelText: 'Get travel insurance in 2 minutes.',
      healthTitle: 'Protect your health', healthText: 'Health insurance — a network of the best clinics.',
      cta: 'Calculate',
    },
    policies: {
      title: 'My policies', subtitle: 'Your issued insurance policies',
      loginNeeded: 'Sign in to see your policies', login: 'Sign in',
      empty: 'No policies yet', emptyCta: 'Choose insurance', until: 'Valid until',
      status: { DRAFT: 'Draft', PENDING: 'Awaiting payment', ACTIVE: 'Active', EXPIRED: 'Expired', CANCELLED: 'Cancelled' },
    },
  },
};

// nav kalitini ham qo'shamiz
const NAV_SUGURTA = { uz: 'Sug‘urta', ru: 'Страхование', en: 'Insurance' };

for (const [lang, file] of Object.entries(FILES)) {
  const json = JSON.parse(readFileSync(file, 'utf8'));
  json.sugurta = NS[lang];
  if (json.nav && typeof json.nav === 'object') json.nav.insurance = NAV_SUGURTA[lang];
  writeFileSync(file, JSON.stringify(json, null, 2) + '\n', 'utf8');
  console.log(`[${lang}] sugurta ns + nav.insurance yozildi`);
}
