import fs from 'node:fs';
const dir = 'apps/web/src/messages';

const data = {
  uz: {
    landing: {
      metaTitle: 'Izla Biznes — homiylar uchun platforma',
      metaDesc: 'Bank, sug‘urta va nasiya kompaniyalari uchun lid oqimi, ranking va analitika. Bir joyda.',
      badge: 'Izla Biznes',
      title: 'Millionlab mijozga bitta platformadan yeting',
      subtitle: 'Izla — bank, sug‘urta va nasiya kompaniyalarini iste’molchi bilan bog‘laydigan super-platforma. Mahsulotingizni joylang, malakali lidlar oling, o‘sishni analitikada kuzating.',
      cta: 'Portalga kirish',
      ctaPlans: 'Tariflarni ko‘rish',
      whyTitle: 'Nega Izla Biznes?',
      value: {
        leads: { title: 'Malakali lidlar', desc: 'Kalkulyatorda summani hisoblab, aynan sizning mahsulotingizni tanlagan tayyor mijozlar.' },
        ranking: { title: 'Yuqori ko‘rinish', desc: 'Tarifga qarab qidiruvda yuqori o‘rin va featured joylashuv — ko‘proq murojaat.' },
        analytics: { title: 'Analitika', desc: 'Ko‘rinish, lid, konversiya va daromadni bitta panelda real vaqtda kuzating.' },
        selfServe: { title: 'O‘zingiz boshqaring', desc: 'Mahsulot, tarif va lidlarni o‘zingiz sozlaysiz — qo‘ng‘iroqsiz, darrov.' },
      },
      plansTitle: 'Oddiy, shaffof tariflar',
      plansSubtitle: 'Oylik obuna. Istalgan vaqtda o‘zgartiring. Yashirin to‘lovlarsiz.',
    },
    portal: {
      metaTitle: 'Izla Biznes portali',
      metaDesc: 'Homiy kabineti — lidlar, mahsulotlar, tarif va analitika.',
      title: 'Izla Biznes portali',
      subtitle: 'Kompaniyangiz, lidlaringiz va tarifingizni boshqaring.',
      loginNeeded: 'Portalga kirish uchun tizimga kiring.',
      login: 'Kirish',
      tab: { overview: 'Umumiy', leads: 'Lidlar', products: 'Mahsulotlar', plan: 'Tarif' },
    },
    onboarding: {
      title: 'Kompaniyangizni ro‘yxatdan o‘tkazing',
      subtitle: 'Bir daqiqada boshlang. Bepul tarif bilan darrov ishga tushasiz.',
      name: 'Brend nomi',
      namePh: 'Masalan: Kafil Sug‘urta',
      legalName: 'Yuridik nom',
      taxId: 'STIR',
      phone: 'Telefon',
      email: 'Email',
      website: 'Veb-sayt',
      submit: 'Kompaniya yaratish',
      note: 'Ro‘yxatdan o‘tish orqali Izla Biznes shartlariga rozilik bildirasiz.',
      done: 'Kompaniya yaratildi',
    },
    overview: {
      products: 'Mahsulotlar',
      leadsTotal: 'Jami lidlar',
      leads30d: 'Lidlar (30 kun)',
      balance: 'Hamyon balansi',
      leadsByChannel: 'Kanal bo‘yicha lidlar',
      until: 'gacha',
      freePlan: 'Bepul tarif',
    },
    leads: {
      all: 'Barchasi',
      empty: 'Hozircha lid yo‘q. Mahsulotlaringiz mijozlarni jalb qila boshlaganda bu yerda paydo bo‘ladi.',
      client: 'Mijoz',
      channel: 'Kanal',
      product: 'Mahsulot',
      amount: 'Summa',
      status: 'Holat',
      date: 'Sana',
    },
    products: {
      empty: 'Sizga biriktirilgan mahsulot yo‘q. Ulash uchun Izla jamoasi bilan bog‘laning.',
      active: 'Faol',
      inactive: 'Faol emas',
      from: 'dan',
    },
    channel: { insurance: 'Sug‘urta', mortgage: 'Ipoteka', nasiya: 'Nasiya', vendor: 'Xizmat' },
    status: { ACTIVE: 'Faol', PENDING: 'Ko‘rib chiqilmoqda', SUSPENDED: 'To‘xtatilgan' },
    plans: {
      popular: 'Ommabop',
      free: 'Bepul',
      month: 'oy',
      choose: 'Tanlash',
      current: 'Joriy tarif',
      activated: 'Tarif faollashtirildi',
      portalHint: 'Tarifni istalgan vaqtda o‘zgartiring. Yuqori tarif — arzonroq lidlar, ko‘proq featured o‘rin va kengroq analitika.',
      FREE: { name: 'Bepul', tagline: 'Sinab ko‘rish uchun' },
      GROWTH: { name: 'O‘sish', tagline: 'O‘sayotgan kompaniyalar uchun' },
      ENTERPRISE: { name: 'Korxona', tagline: 'Yirik hajm uchun' },
    },
    features: {
      listing2: '2 tagacha mahsulot',
      leadsInbox: 'Lidlar inboxi (barcha kanal)',
      basicProfile: 'Kompaniya profili',
      emailSupport: 'Email qo‘llab-quvvatlash',
      listing10: '10 tagacha mahsulot',
      featured1: '1 ta featured o‘rin',
      analytics: 'Analitika paneli',
      leadDiscount15: 'Lidlarga 15% chegirma',
      verifiedBadge: 'Tasdiqlangan nishon',
      prioritySupport: 'Ustuvor qo‘llab-quvvatlash',
      listingUnlimited: 'Cheksiz mahsulot',
      featured5: '5 ta featured o‘rin',
      analyticsPro: 'Kengaytirilgan analitika',
      leadDiscount30: 'Lidlarga 30% chegirma',
      apiAccess: 'API kirish (lead/quote)',
      dedicatedManager: 'Shaxsiy menejer',
    },
  },
  ru: {
    landing: {
      metaTitle: 'Izla Business — платформа для партнёров',
      metaDesc: 'Поток лидов, ранжирование и аналитика для банков, страховых и BNPL-компаний. В одном месте.',
      badge: 'Izla Business',
      title: 'Дотянитесь до миллионов клиентов с одной платформы',
      subtitle: 'Izla — супер-платформа, соединяющая банки, страховые и BNPL-компании с потребителем. Размещайте продукты, получайте квалифицированные лиды, отслеживайте рост в аналитике.',
      cta: 'Войти в портал',
      ctaPlans: 'Смотреть тарифы',
      whyTitle: 'Почему Izla Business?',
      value: {
        leads: { title: 'Квалифицированные лиды', desc: 'Клиенты, которые рассчитали сумму в калькуляторе и выбрали именно ваш продукт.' },
        ranking: { title: 'Больше видимости', desc: 'Высокие позиции в поиске и featured-размещение в зависимости от тарифа — больше обращений.' },
        analytics: { title: 'Аналитика', desc: 'Показы, лиды, конверсия и доход в одной панели в реальном времени.' },
        selfServe: { title: 'Управляйте сами', desc: 'Настраивайте продукты, тариф и лиды самостоятельно — без звонков, сразу.' },
      },
      plansTitle: 'Простые, прозрачные тарифы',
      plansSubtitle: 'Месячная подписка. Меняйте в любой момент. Без скрытых платежей.',
    },
    portal: {
      metaTitle: 'Портал Izla Business',
      metaDesc: 'Кабинет партнёра — лиды, продукты, тариф и аналитика.',
      title: 'Портал Izla Business',
      subtitle: 'Управляйте компанией, лидами и тарифом.',
      loginNeeded: 'Войдите в систему, чтобы открыть портал.',
      login: 'Войти',
      tab: { overview: 'Обзор', leads: 'Лиды', products: 'Продукты', plan: 'Тариф' },
    },
    onboarding: {
      title: 'Зарегистрируйте компанию',
      subtitle: 'Начните за минуту. С бесплатным тарифом запуск мгновенный.',
      name: 'Название бренда',
      namePh: 'Например: Kafil Страхование',
      legalName: 'Юридическое название',
      taxId: 'ИНН',
      phone: 'Телефон',
      email: 'Email',
      website: 'Веб-сайт',
      submit: 'Создать компанию',
      note: 'Регистрируясь, вы соглашаетесь с условиями Izla Business.',
      done: 'Компания создана',
    },
    overview: {
      products: 'Продукты',
      leadsTotal: 'Всего лидов',
      leads30d: 'Лиды (30 дней)',
      balance: 'Баланс кошелька',
      leadsByChannel: 'Лиды по каналам',
      until: 'до',
      freePlan: 'Бесплатный тариф',
    },
    leads: {
      all: 'Все',
      empty: 'Пока нет лидов. Они появятся здесь, когда ваши продукты начнут привлекать клиентов.',
      client: 'Клиент',
      channel: 'Канал',
      product: 'Продукт',
      amount: 'Сумма',
      status: 'Статус',
      date: 'Дата',
    },
    products: {
      empty: 'Нет прикреплённых продуктов. Свяжитесь с командой Izla для подключения.',
      active: 'Активен',
      inactive: 'Неактивен',
      from: 'от',
    },
    channel: { insurance: 'Страхование', mortgage: 'Ипотека', nasiya: 'Рассрочка', vendor: 'Услуга' },
    status: { ACTIVE: 'Активен', PENDING: 'На рассмотрении', SUSPENDED: 'Приостановлен' },
    plans: {
      popular: 'Популярный',
      free: 'Бесплатно',
      month: 'мес',
      choose: 'Выбрать',
      current: 'Текущий тариф',
      activated: 'Тариф активирован',
      portalHint: 'Меняйте тариф в любой момент. Выше тариф — дешевле лиды, больше featured-мест и расширенная аналитика.',
      FREE: { name: 'Бесплатный', tagline: 'Чтобы попробовать' },
      GROWTH: { name: 'Рост', tagline: 'Для растущих компаний' },
      ENTERPRISE: { name: 'Корпоративный', tagline: 'Для больших объёмов' },
    },
    features: {
      listing2: 'До 2 продуктов',
      leadsInbox: 'Инбокс лидов (все каналы)',
      basicProfile: 'Профиль компании',
      emailSupport: 'Поддержка по email',
      listing10: 'До 10 продуктов',
      featured1: '1 featured-место',
      analytics: 'Панель аналитики',
      leadDiscount15: 'Скидка 15% на лиды',
      verifiedBadge: 'Значок «Проверено»',
      prioritySupport: 'Приоритетная поддержка',
      listingUnlimited: 'Безлимит продуктов',
      featured5: '5 featured-мест',
      analyticsPro: 'Расширенная аналитика',
      leadDiscount30: 'Скидка 30% на лиды',
      apiAccess: 'Доступ к API (lead/quote)',
      dedicatedManager: 'Персональный менеджер',
    },
  },
  en: {
    landing: {
      metaTitle: 'Izla Business — a platform for partners',
      metaDesc: 'Lead flow, ranking and analytics for banks, insurers and BNPL providers. In one place.',
      badge: 'Izla Business',
      title: 'Reach millions of customers from one platform',
      subtitle: 'Izla is a super-platform connecting banks, insurers and BNPL providers with consumers. List your products, get qualified leads, track growth in analytics.',
      cta: 'Open portal',
      ctaPlans: 'See plans',
      whyTitle: 'Why Izla Business?',
      value: {
        leads: { title: 'Qualified leads', desc: 'Customers who calculated the amount and chose your exact product — ready to convert.' },
        ranking: { title: 'More visibility', desc: 'Higher search position and featured placement by plan — more inquiries.' },
        analytics: { title: 'Analytics', desc: 'Impressions, leads, conversion and revenue in one real-time dashboard.' },
        selfServe: { title: 'Run it yourself', desc: 'Configure products, plan and leads on your own — no calls, instant.' },
      },
      plansTitle: 'Simple, transparent plans',
      plansSubtitle: 'Monthly subscription. Change anytime. No hidden fees.',
    },
    portal: {
      metaTitle: 'Izla Business portal',
      metaDesc: 'Partner cabinet — leads, products, plan and analytics.',
      title: 'Izla Business portal',
      subtitle: 'Manage your company, leads and plan.',
      loginNeeded: 'Sign in to open the portal.',
      login: 'Sign in',
      tab: { overview: 'Overview', leads: 'Leads', products: 'Products', plan: 'Plan' },
    },
    onboarding: {
      title: 'Register your company',
      subtitle: 'Start in a minute. With the free plan you go live instantly.',
      name: 'Brand name',
      namePh: 'e.g. Kafil Insurance',
      legalName: 'Legal name',
      taxId: 'Tax ID',
      phone: 'Phone',
      email: 'Email',
      website: 'Website',
      submit: 'Create company',
      note: 'By registering you agree to the Izla Business terms.',
      done: 'Company created',
    },
    overview: {
      products: 'Products',
      leadsTotal: 'Total leads',
      leads30d: 'Leads (30 days)',
      balance: 'Wallet balance',
      leadsByChannel: 'Leads by channel',
      until: 'until',
      freePlan: 'Free plan',
    },
    leads: {
      all: 'All',
      empty: 'No leads yet. They will appear here once your products start attracting customers.',
      client: 'Client',
      channel: 'Channel',
      product: 'Product',
      amount: 'Amount',
      status: 'Status',
      date: 'Date',
    },
    products: {
      empty: 'No products attached. Contact the Izla team to connect them.',
      active: 'Active',
      inactive: 'Inactive',
      from: 'from',
    },
    channel: { insurance: 'Insurance', mortgage: 'Mortgage', nasiya: 'Installment', vendor: 'Service' },
    status: { ACTIVE: 'Active', PENDING: 'Under review', SUSPENDED: 'Suspended' },
    plans: {
      popular: 'Popular',
      free: 'Free',
      month: 'mo',
      choose: 'Choose',
      current: 'Current plan',
      activated: 'Plan activated',
      portalHint: 'Change your plan anytime. Higher plan means cheaper leads, more featured slots and deeper analytics.',
      FREE: { name: 'Free', tagline: 'To try it out' },
      GROWTH: { name: 'Growth', tagline: 'For growing companies' },
      ENTERPRISE: { name: 'Enterprise', tagline: 'For large volume' },
    },
    features: {
      listing2: 'Up to 2 products',
      leadsInbox: 'Leads inbox (all channels)',
      basicProfile: 'Company profile',
      emailSupport: 'Email support',
      listing10: 'Up to 10 products',
      featured1: '1 featured slot',
      analytics: 'Analytics dashboard',
      leadDiscount15: '15% off leads',
      verifiedBadge: 'Verified badge',
      prioritySupport: 'Priority support',
      listingUnlimited: 'Unlimited products',
      featured5: '5 featured slots',
      analyticsPro: 'Advanced analytics',
      leadDiscount30: '30% off leads',
      apiAccess: 'API access (lead/quote)',
      dedicatedManager: 'Dedicated manager',
    },
  },
};

for (const lang of ['uz', 'ru', 'en']) {
  const file = `${dir}/${lang}.json`;
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  json.biznes = data[lang];
  fs.writeFileSync(file, JSON.stringify(json, null, 2) + '\n');
  console.log(`✓ ${lang}: biznes qo‘shildi`);
}
